global proc createJointContextProperties()
{
    string $parent = `toolPropertyWindow -q -location`;
    setParent $parent;
    columnLayout "createJointContext";
    text -l "Create Joint Tool";
    setParent ..;
    
    setUITemplate -popTemplate;
}

global proc createJointContextValues( string $toolName )
{
    string $parent = `toolPropertyWindow -q -location`;
    setParent $parent;
    setParent ..;
    
    toolPropertySelect "createJointContext";
}
