
sgPWindow_file_meshGroup_export_winName = "sgPWindow_file_meshGroup_export"
sgPWindow_file_meshGroup_import_winName = "sgPWindow_file_meshGroup_import"

sgPWindow_file_cache_export_winName = "sgPWindow_file_cache_export"
sgPWindow_file_cache_import_winName = "sgPWindow_file_cache_import"

sgPWindow_file_key_export_winName = "sgPWindow_file_key_export"
sgPWindow_file_key_import_winName = "sgPWindow_file_key_import"

sgPWindow_file_keyAndCache_export_winName = "sgPWindow_file_keyAndCache_export"

sgPWindow_file_sceneBakeInfo_export_winName = "sgPWindow_file_sceneBakeInfo_export"
sgPWindow_file_sceneBakeInfo_import_winName = "sgPWindow_file_sceneBakeInfo_import"

sgPWindow_file_camera_export_winName = "sgPWindow_file_camera_export"